project/MiUniversidad/MiUniversidad/urls.py
from django.contrib import admin
from django.urls import path, include 

#from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("", include("core.urls")),
    path("estudiante/", include("estudiante.urls")),
    path("producto/", include("producto.urls")),
  
]

project/MiUniversidad/core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from core.views import  CustomLoginView,index, register
from . import views

app_name = "core"

urlpatterns = [
    path("", index, name="index" ), 
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", register, name="register"),
     path('about/', views.about_view, name='about'),

    ]

    

 

urlpatterns += staticfiles_urlpatterns()

project/MiUniversidad/estudiante/urls.py
from django.urls import path
from estudiante.views import estudiante_list,index

app_name = "estudiante"

urlpatterns = [
    path("", index, name="index" ), 
    path("estudiante/list", estudiante_list, name= "estudiante_list")
 ]

project/MiUniversidad/producto/urls.py
from django.urls import path
from producto.views import index
from producto.views import (
ProductoCategoriaList, 
ProductoCategoriaCreate,
ProductoCategoriaDetail, 
ProductoCategoriaActualizar, 
ProductoCategoriaDelete,
ProductoList,
ProductoCreate,
ProductoDelete,
ProductoDetail,
ProductoActualizar,
)



app_name = "producto"

urlpatterns = [
    path("", index, name="index" ),
    #path("productocategoria/create", productocategoria_create, name="productocategoria_create"),
    #path("productocategoria/delete/<int:pk>", productocategoria_delete, name="productocategoria_delete"),
    #path("productocategoria/detail/<int:pk>", productocategoria_detail, name="productocategoria_detail"),
    #path("productocategoria/list", productocategoria_list, name= "productocategoria_list"),
    #path("productocategoria/actualizar/<int:pk>", productocategoria_actualizar, name="productocategoria_actualizar"),
 ]

urlpatterns += [
    path("productocategoria/list", ProductoCategoriaList.as_view(), name= "productocategoria_list"),
    path("productocategoria/create", ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    path("productocategoria/detail/<int:pk>", ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/actualizar/<int:pk>", ProductoCategoriaActualizar.as_view(), name="productocategoria_actualizar"),
    path("productocategoria/delete/<int:pk>", ProductoCategoriaDelete.as_view, name="productocategoria_delete")
]

urlpatterns += [
    path("producto/list", ProductoList.as_view(), name= "producto_list"),
    path("producto/create", ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", ProductoDetail.as_view(), name="producto_detail"),
    path("producto/actualizar/<int:pk>", ProductoActualizar.as_view(), name="producto_actualizar"),
    path("producto/delete/<int:pk>", ProductoDelete.as_view, name="producto_delete")
]

project/MiUniversidad/core/models.py
from django.db import models

# Create your models here.

project/MiUniversidad/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

project/MiUniversidad/core/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.http import HttpRequest, HttpResponse




def about_view(request):
    return render(request, 'core/about.html')


def index(request):
    return render(request, "core/index.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "core/index.html", {"mensaje": f"Usuario '{username}' creado"})
        ...
    else:
       form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/MiUniversidad/core/templates/core/components/Titulo1.html
<div class="container px-4  py-lg-4">
    <div class="row align-items-center my-5">
            <h1 class="display-4 text-center mb-4 bg-info text-white">
              {{ título}}
            </h1>
        </div>
   </div>        

project/MiUniversidad/core/templates/core/components/card.html
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <h2 class="card-title">{{ título }}</h2>
                <p class="card-text">{{ texto }}</p>
            </div>
            <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
        </div>
    </div>
</div>
</div>

project/MiUniversidad/core/templates/core/components/footer.html
    <!-- Footer-->
    <footer class="py-2 bg-dark fixed-bottom">
        <div class="container px-4 px-lg-5">
          <p class="m-0 text-center text-white">Universidad Nacional De Finanzas todos los derechos reservados</p>
        </div>
    </footer>

project/MiUniversidad/core/templates/core/components/navbar.html
 <!-- Responsive navbar-->
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Universidad Nacional De Finanzas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Menu</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'estudiante:index' %}">Estudiante</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:index' %}">Producto</a></li>
                <li class="nav-item">
                    <a class="nav-link text-bg-info">{{ user.username}}</a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'core:logout' %}" method="post">
                         {% csrf_token %}
                         <button type="submit" class="btn btn-dark">Logout</button>
                    </form>
                </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:login' %}">login</a>
                </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:register' %}">Crear cuenta</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
 