project/MiUniversidad/MiUniversidad/urls.py
from django.contrib import admin
from django.urls import path, include 

#from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("", include("core.urls")),
    path("estudiante/", include("estudiante.urls")),
    path("producto/", include("producto.urls")),
  
]

project/MiUniversidad/core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from core.views import  CustomLoginView,index, register
from . import views

app_name = "core"

urlpatterns = [
    path("", index, name="index" ), 
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", register, name="register"),
     path('about/', views.about_view, name='about'),

    ]

    

 

urlpatterns += staticfiles_urlpatterns()

project/MiUniversidad/core/models.py
from django.db import models

# Create your models here.

project/MiUniversidad/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

project/MiUniversidad/core/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.http import HttpRequest, HttpResponse




def about_view(request):
    return render(request, 'core/about.html')


def index(request):
    return render(request, "core/index.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "core/index.html", {"mensaje": f"Usuario '{username}' creado"})
        ...
    else:
       form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/MiUniversidad/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Acerca de Nuestra Universidad</h2>
        <p>Somos una institución de educación superior con más de 20 años de experiencia en la enseñanza de las finanzas y la economía. Nos enorgullece ofrecer a nuestros estudiantes una educación de excelencia que les prepare para ser líderes en el mundo de los negocios.</p>
      </div>
      <div class="col-md-6">
        <h2>Nuestra Misión</h2>
        <p>Nuestra misión es formar profesionales altamente capacitados en las áreas financieras, contables y económicas, proporcionándoles las herramientas y conocimientos necesarios para que puedan tomar decisiones estratégicas y contribuir al desarrollo sostenible de las empresas y la sociedad.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h2>Nuestros Valores</h2>
        <ul>
          <li>Excelencia académica</li>
          <li>Integridad y ética profesional</li>
          <li>Innovación y espíritu emprendedor</li>
          <li>Responsabilidad social</li>
        </ul>
      </div>
      <div class="col-md-6">
        <h2>Nuestro Equipo</h2>
        <p>Nuestro equipo docente está conformado por profesionales altamente calificados, con amplia experiencia en el sector financiero y empresarial. Están comprometidos con la formación integral de nuestros estudiantes y con el desarrollo de la investigación en finanzas.</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

project/MiUniversidad/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

     {% include 'core/components/navbar.html' %}
        
       <div class="container px-4  py-lg-4">
        <div class="row align-items-center my-5">
                <h1 class="display-4 text-center mb-4 bg-info text-white">
                   {% block body_title %}
                   {% endblock body_title %}
                </h1>
            </div>
            {% block content %}
            
            {% endblock content %}
       </div>        
       
       {% include 'core/components/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    </body>
</html>

project/MiUniversidad/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
    U.N.A.F
{% endblock title %}

{% block body_title %}
Menu
{% endblock body_title %}

{% block content %}


 
<!-- Page Content-->
<div class="container px-4 px-lg-5">

     {% if user.is_authenticated %}
        <p class="text-info "> Sea bienvenido {{user.username}}</p>
     {% endif %}

      {% if mensaje %}
      <p class="text-info ">{{ mensaje }} Sea bienvenido</p>
      {% endif %}

    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" 
            src="{% static 'core/imagen/logo.unaf-.webp' %}" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">Universidad Nacional De Finanzas</h1>
            <p>La Universidad Nacional de Finanzas (UNAF) es una institución pública de educación superior ubicada en la ciudad de Buenos Aires, Argentina. Fue fundada en 1985 con el objetivo de formar profesionales altamente capacitados en el área de las finanzas y la economía.</p>
            <a class="btn btn-primary" href="https://wa.me/1158403375" target="_blank">Comunicate con nosotros</a>
            <li><a href="{% url 'core:about' %}">Sobre Nosotros</a></li>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">La Universidad de Finanzas</h2>
                    <p class="card-text">La Universidad de Finanzas es una prestigiosa institución académica que se enfoca en la formación de expertos en el campo de las finanzas.</p>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- Content Row-->
    <div class="container-fluid my-5">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
                <div class="card h-100 shadow">
                    <img src="https://picsum.photos/id/1/300/200" class="card-img-top" alt="Tarjeta 1">
                    <div class="card-body">
                        <h5 class="card-title">Promociones</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100 shadow">
                    <img src="https://picsum.photos/id/2/300/200" class="card-img-top" alt="Tarjeta 2">
                    <div class="card-body">
                        <h5 class="card-title">Inscripciones</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100 shadow">
                    <img src="https://picsum.photos/id/3/300/200" class="card-img-top" alt="Tarjeta 3">
                    <div class="card-body">
                        <h5 class="card-title">Carreras</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100 shadow">
                    <img src="https://picsum.photos/id/4/300/200" class="card-img-top" alt="Tarjeta 4">
                    <div class="card-body">
                        <h5 class="card-title">Sucursales</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100 shadow">
                    <img src="https://picsum.photos/id/5/300/200" class="card-img-top" alt="Tarjeta 5">
                    <div class="card-body">
                        <h5 class="card-title">Cupos</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white"> </p></div>
</footer>
{% endblock content %}

project/MiUniversidad/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
   Universidad Nacional De Finanzas
{% endblock title %}

{% block body_title %}
 Login
{% endblock body_title %}

{% block content %}
   
<form method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <input type="hidden" name="next" value="{% url 'core:index' %}">
    </table>
      <button type="submit" class="btn btn-primary ">Iniciar Sesión Como Estudiante</button>
      <a href="{% url 'core:index' %}" class="btn btn-secondary ">Cancelar</a>
</form>
    
{% endblock content %}

project/MiUniversidad/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block title %}
Universidad Nacional De Finanzas
{% endblock title %}

{% block body_title %}
Cerrar sesion
{% endblock body_title %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center"> 
      <div class="col-lg-6 col-md-8 col-sm-10"> 
         <div class="card shadow-sm">
             <div class="card-body"> 
               <form method="post"> 
                  <p class="fs-5 text-center">Sesión cerrada exitosamente</p>
                   <p class="text-center">Gracias por utilizar nuestros servicios. Esperamos que haya tenido una experiencia satisfactoria. ¡Que tenga un buen día!</p> 
<div class="d-grid gap-2"> 
  
</div> 
</form>
 </div> 
</div> 
</div> 
</div> 
</div> 
{% endblock content %}

project/MiUniversidad/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block title %}
   Register
{% endblock title %}

{% block body_title %}
  Nuevo usuario
{% endblock body_title %}

{% block content %}
   
<form method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
      <button type="submit" class="btn btn-primary ">Registrarse</button>
      <a href="{% url 'core:index' %}" class="btn btn-secondary ">Cancelar</a>
</form>
    
{% endblock content %}