project/MiUniversidad/MiUniversidad/urls.py
from django.contrib import admin
from django.urls import path, include 

#from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("", include("core.urls")),
    path("estudiante/", include("estudiante.urls")),
    path("producto/", include("producto.urls")),
  
]

project/MiUniversidad/core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from core.views import  CustomLoginView,index, register
from . import views

app_name = "core"

urlpatterns = [
    path("", index, name="index" ), 
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", register, name="register"),
     path('about/', views.about_view, name='about'),

    ]

    

 

urlpatterns += staticfiles_urlpatterns()

project/MiUniversidad/producto/urls.py
from django.urls import path
from producto.views import index
from producto.views import (
ProductoCategoriaList, 
ProductoCategoriaCreate,
ProductoCategoriaDetail, 
ProductoCategoriaActualizar, 
ProductoCategoriaDelete,
ProductoList,
ProductoCreate,
ProductoDelete,
ProductoDetail,
ProductoActualizar,
)



app_name = "producto"

urlpatterns = [
    path("", index, name="index" ),
    #path("productocategoria/create", productocategoria_create, name="productocategoria_create"),
    #path("productocategoria/delete/<int:pk>", productocategoria_delete, name="productocategoria_delete"),
    #path("productocategoria/detail/<int:pk>", productocategoria_detail, name="productocategoria_detail"),
    #path("productocategoria/list", productocategoria_list, name= "productocategoria_list"),
    #path("productocategoria/actualizar/<int:pk>", productocategoria_actualizar, name="productocategoria_actualizar"),
 ]

urlpatterns += [
    path("productocategoria/list", ProductoCategoriaList.as_view(), name= "productocategoria_list"),
    path("productocategoria/create", ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    path("productocategoria/detail/<int:pk>", ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/actualizar/<int:pk>", ProductoCategoriaActualizar.as_view(), name="productocategoria_actualizar"),
    path("productocategoria/delete/<int:pk>", ProductoCategoriaDelete.as_view, name="productocategoria_delete")
]

urlpatterns += [
    path("producto/list", ProductoList.as_view(), name= "producto_list"),
    path("producto/create", ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", ProductoDetail.as_view(), name="producto_detail"),
    path("producto/actualizar/<int:pk>", ProductoActualizar.as_view(), name="producto_actualizar"),
    path("producto/delete/<int:pk>", ProductoDelete.as_view, name="producto_delete")
]

project/MiUniversidad/producto/models.py
from django.db import models
from django.utils import timezone

class ProductoCategoria(models.Model):
    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "categoría de producto"
        verbose_name_plural = "categorías de producto"

class Producto(models.Model):
    categoria_id = models.ForeignKey(ProductoCategoria, null=True, blank=True, on_delete=models.SET_NULL)
    nombre = models.CharField(max_length=200)
    unidad_de_medida = models.CharField(max_length=200)
    cantidad = models.FloatField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField(null=True, blank=True, editable=True, default=timezone.now)

    def __str__(self):
        return f"{self.nombre} ({self.unidad_de_medida} ${self.precio:.2f})"

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

project/MiUniversidad/producto/forms.py
from django import forms

from . import models

class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = ["nombre", "descripcion"]

class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = '__all__'
    template_name= "productoform.html"
     

project/MiUniversidad/producto/views.py
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from producto.models import ProductoCategoria, Producto
from producto.forms import ProductoCategoriaForm, ProductoForm

def index(request):
    return render(request, "producto/index.html")

class ProductoCategoriaList(ListView):
    model = ProductoCategoria

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            queryset = queryset.filter(
                Q(nombre__icontains=busqueda) | Q(descripcion__icontains=busqueda)
            )
        return queryset

class ProductoCategoriaCreate(LoginRequiredMixin, CreateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")

class ProductoCategoriaDetail(DetailView):
    model = ProductoCategoria

class ProductoCategoriaActualizar(UpdateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")

class ProductoCategoriaDelete(DeleteView):
    model = ProductoCategoria
    success_url = reverse_lazy("producto:productocategoria_list")

class ProductoList(ListView):
    model = Producto

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            queryset = queryset.filter(nombre__icontains=busqueda)
        return queryset

class ProductoCreate(CreateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("producto:producto_list")

class ProductoDetail(DetailView):
    model = Producto

class ProductoActualizar(UpdateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("producto:producto_list")

class ProductoDelete(DeleteView):
    model = Producto
    success_url = reverse_lazy("producto:producto_list")

project/MiUniversidad/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block title %}
    Producto
{% endblock title %}

{% block body_title %}
 App Producto
{% endblock body_title %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h3 class="card-title">Categorías de Producto</h3>
        <div class="pb-4">
            <a href="{% url 'producto:productocategoria_list' %}" class="card-link">Todas las categorías de productos</a>
        </div>
        <div class="pb-4">
            <a href="{% url 'producto:productocategoria_create' %}" class="card-link">Crear categoría de producto</a>
        </div>
    </div>
</div>

<div class="card mt-4">
    <div class="card-body">
        <h3 class="card-title">Productos</h3>
        <div class="pb-4">
            <a href="{% url 'producto:producto_list' %}" class="card-link">Todos los productos</a>
        </div>
        <div class="pb-4">
            <a href="{% url 'producto:producto_create' %}" class="card-link">Crear producto</a>
        </div>
    </div>
</div>

{% endblock content %}

project/MiUniversidad/producto/templates/producto/producto_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
Producto |  Productos
{% endblock title %}
 
{% block body_title %}
{% if form.instance.pk %}
     Producto -  Producto: Descartar

{% endblock body_title %}

{% block content %}

<p class="fs-5 fst-italic">¿ Estas seguro que quieres descartar los cambios de "{{ object.nombre }}"?</p>
<form method="post">
  {% csrf_token %}
 
  <button type="submit">Confirmar</button>

</form>
<a href="{% url 'producto:index' %}">Regresar</a>
{% endblock content %}


 

project/MiUniversidad/producto/templates/producto/producto_list.html
{% extends 'core/base.html' %}

{% block title %}
Producto | Lista
{% endblock title %}
 
{% block body_title %}
Producto : Todos los productos
{% endblock body_title %}

{% block content %}
{% if object_list %}
    

<div class="container">
    <table class="table table-striped table-bordered table-hover table-responsive"> 
        <thead class="thead-dark"> 
            <tr> 
                <th>Nombre</th> 
                <th>Precio</th> 
                <th>Categoría</th> 
                <th>Acciones</th> 
            </tr> 
        </thead> 
        <tbody> 
            {% for producto in object_list %} 
            <tr> 
                <td>{{ producto.nombre }}</td> 
                <td>{{ producto.precio }}</td> 
                <td>{{ producto.categoria }}</td> 
                <td> 
                    <a href="{% url 'producto:producto_detail' producto.id %}" class="btn btn-primary btn-sm">Detalle</a> 
                    <a href="{% url 'producto:producto_detail' producto.id %}" class="btn btn-warning btn-sm">Editar</a> 
                    <a href="{% url 'producto:producto_actualizar' producto.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
            
            {% endfor %} 
        </tbody>
    </table>
    
</tbody> 
</table>
{% else %}
<p class="fs-3">No Hay Registros</p>
{% endif %}
</div>
    </div>

    
{% endblock content %}

 

project/MiUniversidad/producto/templates/producto/productocategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}
Producto | Categoria de Productos
{% endblock title %}
 
{% block body_title %}
{% if form.instance.pk %}
     Producto - Categorias de Producto: Descartar

{% endblock body_title %}

{% block content %}

<p class="fs-5 fst-italic">¿ Estas seguro que quieres descartar los cambios de "{{ object.nombre }}"?</p>
<form method="post">
  {% csrf_token %}
 
  <button type="submit">Confirmar</button>

</form>
<a href="{% url 'producto:index' %}">Regresar</a>
{% endblock content %}


 

project/MiUniversidad/producto/templates/producto/productocategoria_detail.html
{% extends 'core/base.html' %}

{% block title %}
Producto | Categorias de Productos
{% endblock title %}
 
{% block body_title %}
Producto - Categorias de Productos: detalles de producto
{% endblock body_title %}

{% block content %}
<div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">Nombre:{{ object.nombre }}</h5>
      <p class="card-text">Descripción{{ object.descripcion }}</p>
      <a href="{% url 'producto:productocategoria_list' %}" class="btn btn-secondary">Atrás</a>
    </div>
    <div class="card-footer d-flex justify-content-end">
    </div>
  </div>
  
    
{% endblock content %}

 

project/MiUniversidad/producto/templates/producto/productocategoria_form.html
{% extends 'core/base.html' %}

{% block title %}
Producto | Categoria de Productos
{% endblock title %}
 
{% block body_title %}
{% if form.instance.pk %}
     Producto - Categorias de Producto: Edición
{% else %}
    Producto - Categorias de Productos: Creación
{% endif %}
Producto : Todos los productos > Creación
{% endblock body_title %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  {% if form.errors %}
<script>
  var errors = '';
  Swal.fire({
    title: 'Error!',
    text: errors,
    icon: 'error',
  });
</script>
{% endif %}
  <button type="submit">Guardar</button>

</form>
{% endblock content %}


 

project/MiUniversidad/producto/templates/producto/productocategoria_list.html
{% extends 'core/base.html' %}

{% block title %}
Producto | Lista De Categoria De Producto
{% endblock title %}
 
{% block body_title %}
Producto : Listado de Productos
{% endblock body_title %}

{% block content %}
<div class="container">
    <table class="table table-striped table-bordered table-hover table-responsive"> 
        <thead class="thead-dark"> 
            <tr> 
                <th>Nombre</th> 
                <th>Precio</th> 
                <th>Categoría</th> 
                <th>Acciones</th> 
            </tr> 
        </thead> 
        <tbody> 
            {% for producto in object_list %} 
            <tr> 
                <td>{{ producto.nombre }}</td> 
                <td>{{ producto.precio }}</td> 
                <td>{{ producto.categoria }}</td> 
                <td> 
                    <a href="{% url 'producto:productocategoria_detail' producto.id %}" class="btn btn-primary btn-sm">Detalle</a> 
                    <a href="{% url 'producto:productocategoria_detail' producto.id %}" class="btn btn-warning btn-sm">Editar</a> 
                    <a href="{% url 'producto:productocategoria_actualizar' producto.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
            {% endfor %} 
        </tbody>
    </table>
</div>

            </tbody> 
        </table>
    </div>

    
{% endblock content %}

 

project/MiUniversidad/producto/templates/producto/productodetail.html
{% extends 'core/base.html' %}

{% block title %}
Producto | Productos
{% endblock title %}
 
{% block body_title %}
Producto - Productos: detalles de producto
{% endblock body_title %}

{% block content %}
<div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">Categoria:{{ object.categoria_id }}</h5>
      <p class="card-text">Nombre{{ object.nombre }}</p>
      <p class="card-text">Precio{{ object.nombre }}</p>
      <p class="card-text">Cantidad{{ object.cantidad }}</p>
      <a href="{% url 'producto:productocategoria_list' %}" class="btn btn-secondary">Atrás</a>
    </div>
    <div class="card-footer d-flex justify-content-end">
    </div>
  </div>
  
    
{% endblock content %}

 

project/MiUniversidad/producto/templates/producto/productoform.html
{% extends 'core/base.html' %}

{% block title %}
Producto |  Productos
{% endblock title %}
 
{% block body_title %}
{% if form.instance.pk %}
     Producto -  Producto: Edición
{% else %}
    Producto -  Productos: Creación
{% endif %}
Producto : Todos los productos > Creación
{% endblock body_title %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  {% if form.errors %}
<script>
  var errors = '';
  Swal.fire({
    title: 'Error!',
    text: errors,
    icon: 'error',
  });
</script>
{% endif %}
  <button type="submit">Guardar</button>

</form>
{% endblock content %}


 