project/MiUniversidad/MiUniversidad/urls.py
from django.contrib import admin
from django.urls import path, include 

#from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("", include("core.urls")),
    path("estudiante/", include("estudiante.urls")),
    path("producto/", include("producto.urls")),
  
]

project/MiUniversidad/core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from core.views import  CustomLoginView,index, register
from . import views

app_name = "core"

urlpatterns = [
    path("", index, name="index" ), 
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", register, name="register"),
     path('about/', views.about_view, name='about'),

    ]

    

 

urlpatterns += staticfiles_urlpatterns()

project/MiUniversidad/estudiante/urls.py
from django.urls import path
from estudiante.views import estudiante_list,index

app_name = "estudiante"

urlpatterns = [
    path("", index, name="index" ), 
    path("estudiante/list", estudiante_list, name= "estudiante_list")
 ]

project/MiUniversidad/estudiante/models.py
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=200, unique=True)

    def __str__(self):
       return self.nombre
    
    class Meta:
       verbose_name = "país"
       verbose_name_plural = "países"

class Estudiante(models.Model):
    nombre = models.CharField(max_length=250)
    apellido = models.CharField(max_length=250)
    nacimiento = models.DateField(null=True, blank=True)
    pais_origen_fk = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="pais de origen")

    def __str__(self):
        return f"{self.apellido}, {self.nombre}"
class Meta:
    verbose_name = "estudiante"
    verbose_name_plural = "estudiantes"

project/MiUniversidad/estudiante/views.py
from django.shortcuts import render
from estudiante.models import Estudiante
def index(request):
    return render(request, "estudiante/index.html")


def estudiante_list(request):
    consulta = Estudiante.objects.all()
    contexto = {"estudiantes":consulta}
    return render(request, "estudiante/estudiante_list.html", contexto)

project/MiUniversidad/estudiante/templates/estudiante/estudiante_list.html
{% extends 'core/base.html' %}

{% block title %}
    Estudiante | Lista
{% endblock title %}
 
{% block body_title %}
 Estudiante : Todos los estudiantes
{% endblock body_title %}

{% block content %}

{% for estudiante in estudiantes %}
<ul>
    <li><p>Nombre:{{ estudiante.nombre}}</p></li>
    <li><p>Apellido:{{ estudiante.apellido}}</p></li>
    <li><p>Nacimiento:{{ estudiante.nacimiento}}</p></li>
    {% if estudiante.pais_origen_fk %}
    <li><p>Pais:{{ estudiante.pais_origen_fk}}</p></li>
    {% else %}
    <li><p>Pais: "No hay registro"</p></li>
    {% endif %}
    
</ul>
{% endfor %}
{% endblock content %}

 

project/MiUniversidad/estudiante/templates/estudiante/index.html
{% extends 'core/base.html' %}

{% block title %}
    Estudiante
{% endblock title %}

{% block body_title %}
 App Estudiante
{% endblock body_title %}


{% block content %}
     <div>
        <a href="{% url 'estudiante:estudiante_list' %}">Todos los estudiantes</a>
    </div>
{% endblock content %}